package foxxware;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/**
 *
 * @author cat
 */
public class ordersMack extends javax.swing.JFrame {
    
    public static String order;
    public static int oneortwo=0;
        public String[][] send = new String[500][5];
 public String[][] multD = new String[500][4];
   
    public Object superselect;
    public Object superprice;
    public Object superprice2;
    public String one;
            public String two;
            public String three;
            public String runner;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        combobox = new javax.swing.JComboBox();
        try{

            Connection conn = DriverManager.getConnection("jdbc:mysql://198.23.57.27/corand_ei", "corand_ei","heyheyhey");

            ArrayList<String> cats = new ArrayList<String>();
            String query = "SELECT company FROM companies ORDER BY rownum";
            java.sql.PreparedStatement stm = conn.prepareStatement(query);

            ResultSet rs = stm.executeQuery(query);

            while(rs.next()){
                String cat = rs.getString("company");

                cats.add(cat);
            }

            rs.close();

            // populate the combo box
            DefaultComboBoxModel model = new DefaultComboBoxModel(cats.toArray());
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jScrollPane2 = new javax.swing.JScrollPane();
            texts = new javax.swing.JTextArea();
            jScrollPane3 = new javax.swing.JScrollPane();
            address1 = new javax.swing.JTextArea();
            jLabel3 = new javax.swing.JLabel();
            jTextField1 = new javax.swing.JTextField();
            jLabel6 = new javax.swing.JLabel();
            jFormattedTextField1 = new javax.swing.JFormattedTextField();
            jScrollPane6 = new javax.swing.JScrollPane();
            jTable4 = new javax.swing.JTable();
            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            jLabel4 = new javax.swing.JLabel();
            jTextField2 = new javax.swing.JTextField();
            jComboBox2 = new javax.swing.JComboBox();
            jLabel5 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            jCheckBox1 = new javax.swing.JCheckBox();
            jCheckBox2 = new javax.swing.JCheckBox();
            jButton5 = new javax.swing.JButton();
            jButton6 = new javax.swing.JButton();
            jTextField3 = new javax.swing.JTextField();
            jLabel9 = new javax.swing.JLabel();
            jTextField4 = new javax.swing.JTextField();
            jScrollPane8 = new javax.swing.JScrollPane();
            jTable5 = new javax.swing.JTable();

            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jScrollPane1.setViewportView(jTable1);

            jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jScrollPane4.setViewportView(jTable2);

            jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jScrollPane5.setViewportView(jTable3);

            jTextArea1.setColumns(20);
            jTextArea1.setRows(5);
            jScrollPane7.setViewportView(jTextArea1);

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            addWindowStateListener(new java.awt.event.WindowStateListener() {
                public void windowStateChanged(java.awt.event.WindowEvent evt) {
                    formWindowStateChanged(evt);
                }
            });
            addWindowFocusListener(new java.awt.event.WindowFocusListener() {
                public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                    formWindowGainedFocus(evt);
                }
                public void windowLostFocus(java.awt.event.WindowEvent evt) {
                }
            });
            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosed(java.awt.event.WindowEvent evt) {
                    formWindowClosed(evt);
                }
                public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
                }
            });

            combobox.setModel(model);
            combobox.setModel(model);
        }catch (Exception io){io.printStackTrace();}
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        jLabel1.setText("Billto Address");

        jLabel2.setText("Shipto Address");

        texts.setColumns(20);
        texts.setRows(5);
        jScrollPane2.setViewportView(texts);

        address1.setColumns(20);
        address1.setRows(5);
        jScrollPane3.setViewportView(address1);

        jLabel3.setText("Customer PO Number");

        jLabel6.setText("OrderDate");

        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yy");
        Date date = new Date();
        jFormattedTextField1.setText(dateFormat.format(date));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {"Part Name", "Mack Price", "Cust Price", "Quantity", "Total"}

        ));
        jScrollPane6.setViewportView(jTable4);

        jButton1.setText("Submit");

        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });

        jLabel4.setText("Order Number");

        jTextField2.setEditable(false);
        jTextField2.setName("supermom"); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Free Shipping (Dayton)", "UPS Ground", "UPS Red", "UPS Blue" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Total Price: ");

        jLabel7.setText("0.00");

        jLabel8.setText("Shipping Option");

        jCheckBox1.setText("Quote");

        jCheckBox2.setText("Direct Ship");

        jButton5.setText("Search");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton5MouseReleased(evt);
            }
        });

        jButton6.setText("Add");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton6MouseReleased(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Quantity");

        jTextField4.setBackground(new java.awt.Color(102, 102, 255));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            multD,
            new String [] {
                "Part Name", "Description", "Mack Price", "Cust Price"
            }
        ));
        jTable5.setToolTipText("Select an Item and Press Add");
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jTable5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jFormattedTextField1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox1)
                        .addComponent(jCheckBox2)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public ordersMack() throws FileNotFoundException, UnsupportedEncodingException {
        initComponents();
   jTable4.getColumnModel().getColumn(0).setPreferredWidth(200);
    long timer = System.currentTimeMillis() / 1000L;
     String alex = Long.toString(timer);
     jTextField2.setText(alex);
     order = alex;
     
             
     PrintWriter writer = new PrintWriter("donotdelete.txt","UTF-8");
writer.println(alex);
writer.close();
     
     
    }
    
    
    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
setVisible(false); //you can't see me!
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseReleased

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed

        int company = combobox.getSelectedIndex()+1;
        String newline = System.getProperty("line.separator");
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://198.23.57.27/corand_ei", "corand_ei","heyheyhey");
            String query = "SELECT company FROM companies WHERE rownum="+company;
            String query1 = "SELECT address FROM companies WHERE rownum="+company;
            String query2 = "SELECT address2 FROM companies WHERE rownum="+company;
            String query3 = "SELECT city FROM companies WHERE rownum="+company;
            String query4 = "SELECT state FROM companies WHERE rownum="+company;
            String query5 = "SELECT zip FROM companies WHERE rownum="+company;
            java.sql.PreparedStatement stm = conn.prepareStatement(query);

            ResultSet rs = stm.executeQuery(query);

            while(rs.next()){
                String cat = rs.getString("company");
                address1.setText(cat);

            }

            java.sql.PreparedStatement stm1 = conn.prepareStatement(query1);

            ResultSet rs1 = stm1.executeQuery(query1);

            while(rs1.next()){
                String cat1 = rs1.getString("address");
                address1.append("\n"+cat1);

            }

            java.sql.PreparedStatement stm2 = conn.prepareStatement(query2);

            ResultSet rs2 = stm2.executeQuery(query2);

            while(rs2.next()){
                String cat2 = rs2.getString("address2");
                address1.append(cat2);

            }

            java.sql.PreparedStatement stm3 = conn.prepareStatement(query3);

            ResultSet rs3 = stm3.executeQuery(query3);

            while(rs3.next()){
                String cat3 = rs3.getString("city");
                address1.append("\n"+cat3+" ");

            }

            java.sql.PreparedStatement stm4 = conn.prepareStatement(query4);

            ResultSet rs4 = stm4.executeQuery(query4);

            while(rs4.next()){
                String cat4 = rs4.getString("state");
                address1.append(cat4+" ");

            }

            java.sql.PreparedStatement stm5 = conn.prepareStatement(query5);

            ResultSet rs5 = stm5.executeQuery(query5);

            while(rs5.next()){
                String cat5 = rs5.getString("zip");
                address1.append(cat5);

            }

            rs.close();
            rs1.close();
            rs2.close();
            rs3.close();
            rs4.close();
            rs5.close();

            texts.setText(address1.getText());

        }catch(Exception io){

            io.printStackTrace();
        }
    }//GEN-LAST:event_comboboxActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
//makes main menu pop back up after exiting orders
        
        
        mainMenu reOpen = new mainMenu();
        reOpen.setLocationRelativeTo(null);
        reOpen.toFront();
reOpen.setVisible(true);
String user = System.getProperty("user.name");
        ImageIcon icon = new ImageIcon("images//icon.jpg");
        
        reOpen.setIconImage(icon.getImage());              // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
   // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void jButton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseReleased
        try{populate();}catch(Exception io){System.out.print(io);}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseReleased

    
    
        public void populate() throws ClassNotFoundException, SQLException{
        
        
        
   
  
              	Class.forName("com.mysql.jdbc.Driver");
Connection conn = DriverManager.getConnection("jdbc:mysql://198.23.57.27/corand_ei", "corand_ei","heyheyhey");
         String finishedsearch=jTextField4.getText();
        
        String search="'%"+finishedsearch+"%'";
               
                
        System.out.println("test");
        java.sql.Statement sta = conn.createStatement();
		String Sql = "SELECT * " +
"FROM inventory WHERE partnum LIKE "+search;
		ResultSet rs = sta.executeQuery(Sql);
		 int i=0;
                 
                while (rs.next()) {
              
                  multD[i][0]=rs.getString("partnum");
                  multD[i][1]=rs.getString("desc");
                  multD[i][2]=rs.getString("ourprice");
                  multD[i][3]=rs.getString("yourprice");
                  
 i++;

 
		}
        
                jTable5.setModel(new javax.swing.table.DefaultTableModel(
            multD,
            new String [] {
                "Part Name", "Description", "Mack Price", "Cust Price"
            }
        ));
                
                
    }
    
    
    private void jButton6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseReleased

        //MAKES SURE QUANTITY IS NOT 0
        String stupid = jTextField2.getText();
        if(stupid.equals("")|| stupid.equals(null)){stupid = "1";}

        jTextField2.setText(stupid);

        //MAKES SURE ITEM  IS NOT EMPTY.

        try {Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://198.23.57.27/corand_ei", "corand_ei","heyheyhey");

            PreparedStatement preparedStatement = null;

            if (superselect==null)
            {
                System.out.println("SHITS EMPTY.") ;
            }

            else{System.out.println("SHITS NOT EMPTY");

                System.out.println("testing order creation");
                java.sql.Statement sta = conn.createStatement();
                String Sql = "INSERT INTO `mackorders`(`id`, `item`, `quantity`, `mackprice`, `custprice`) VALUES (?, ?, ?, ?, ?)";

                preparedStatement = conn.prepareStatement(Sql);
int comparingNum ;
                String comparingQ = jTextField3.getText();
                
                if(comparingQ.equals("")||comparingQ.equals(null)||comparingQ.equals(0))
                {
                    comparingQ="1";
                    jTextField3.setText("1");
                }
                
                {
                        
                        }
                preparedStatement.setString(1,jTextField2.getText());
                preparedStatement.setString(2,superselect.toString());
                preparedStatement.setString(3,comparingQ);
                preparedStatement.setString(4,superprice.toString());
                preparedStatement.setString(5,superprice2.toString());

                System.out.println(superselect.toString());
                System.out.println(jTextField2.getText());
                System.out.println(superprice.toString());

                preparedStatement.executeUpdate();
supermethod();
            }
        }catch (Exception io){System.out.println(io);}

    }//GEN-LAST:event_jButton6MouseReleased

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        int row = jTable5.rowAtPoint(evt.getPoint());

        superselect = jTable5.getValueAt(row, 0);

        superprice = jTable5.getValueAt(row, 2);
        superprice2 = jTable5.getValueAt(row, 3);

        System.out.println(superprice);
        System.out.println(superselect);
        // THIS thing sees which row is selected when adding an item. The top
        // looks at the location and gives you the first col (item name) automatically.
        // It then sends the information to the 'superselect' variable which is used
        // at the addbutton event.
    }//GEN-LAST:event_jTable5MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    
    private void supermethod()
    {
        
        try{
    
     Class.forName("com.mysql.jdbc.Driver");
Connection conn = DriverManager.getConnection("jdbc:mysql://198.23.57.27/corand_ei", "corand_ei","heyheyhey");
         String finishedsearch=jTextField1.getText();
        
        String search= order;
               
         
        java.sql.Statement sta = conn.createStatement();
		String Sql = "SELECT * " +
"FROM mackorders WHERE id LIKE "+search;
		ResultSet rs = sta.executeQuery(Sql);
		 int i=0;
                 
                while (rs.next()) {
              
                  send[i][0]=rs.getString("item");
                  send[i][1]=rs.getString("mackprice");
                  send[i][2]=rs.getString("custprice");
                  send[i][3]=rs.getString("quantity");
                  
                  int onetimes = Integer.parseInt(send[i][2]);
                  int twotimes = Integer.parseInt(send[i][3]);
                  
                  int threetimes = onetimes * twotimes;
                  
                
                String five=  Integer.toString(threetimes);
                  send[i][4]= five;
                  
                System.out.println(onetimes);
                System.out.println(twotimes);
                System.out.println(five); 
 i++;

 
		}
 
  
     }catch(Exception io){System.out.println(io);}
        
               jTable4.setModel(new javax.swing.table.DefaultTableModel(
            send,
            
          new String [] {
                "Part Name", "Mack Price", "Cust Price", "Quantity", "Total"}
            ));
             jTable4.getColumnModel().getColumn(0).setPreferredWidth(200);

   






    }
    
    
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ordersMack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ordersMack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ordersMack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ordersMack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ordersMack().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ordersMack.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(ordersMack.class.getName()).log(Level.SEVERE, null, ex);
                }
       
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address1;
    private javax.swing.JComboBox combobox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextArea texts;
    // End of variables declaration//GEN-END:variables
}
